<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 1: Data Analysis of Singapore Rainfall

--- 
# Part 1

Part 1 requires knowledge of basic Python.

---

### Contents:
- [Background](#Background)
- [Data Import & Cleaning](#Data-Import-and-Cleaning)
- [Exploratory Data Analysis](#Exploratory-Data-Analysis)
- [Data Visualization](#Visualize-the-Data)
- [Conclusions and Recommendations](#Conclusions-and-Recommendations)

## Background

According to the [Meteorological Services Singapore](http://www.weather.gov.sg/climate-climate-of-singapore/#:~:text=Singapore%20is%20situated%20near%20the,month%2Dto%2Dmonth%20variation.), Singapore has typical tropical climate with adundant rainfall, high and uniform temperatures and high humidity all year round, since its situated near the equator. There are many factors that help us understand the climate of a country and in this project we are going to look into a few, especially rainfall.

Singapore’s climate is characterised by two main monsoon seasons separated by inter-monsoonal periods.  The **Northeast Monsoon** occurs from December to early March, and the **Southwest Monsoon** from June to September.

The major weather systems affecting Singapore that can lead to heavy rainfall are:

-Monsoon surges, or strong wind episodes in the Northeast Monsoon flow bringing about major rainfall events;

-Sumatra squalls, an organised line of thunderstorms travelling eastward across Singapore, having developed over the island of Sumatra or Straits of Malacca west of us;

-Afternoon and evening thunderstorms caused by strong surface heating and by the sea breeze circulation that develops in the afternoon.

Singapore’s climate station has been located at several different sites in the past 140 years. The station had been decommissioned at various points in the past due to changes to local land use in the site’s vicinity, and had to be relocated. Since 1984, the climate station has been located at **Changi**.

There are other metrics of climate such as temperature, humidity, sun shine duration, wind speed, cloud cover etc. All the dataset used in the project comes from [data.gov.sg](data.gov.sg), as recorded at the Changi climate station

### Choose your Data

There are 2 datasets included in the [`data`](./data/) folder for this project. These correponds to rainfall information. 

* [`rainfall-monthly-number-of-rain-days.csv`](./data/rainfall-monthly-number-of-rain-days.csv): Monthly number of rain days from 1982 to 2022. A day is considered to have “rained” if the total rainfall for that day is 0.2mm or more.
* [`rainfall-monthly-total.csv`](./data/rainfall-monthly-total.csv): Monthly total rain recorded in mm(millimeters) from 1982 to 2022

Other relevant weather datasets from [data.gov.sg](data.gov.sg) that you can download and use are as follows:

* [Relative Humidity](https://data.gov.sg/dataset/relative-humidity-monthly-mean)
* [Monthly Maximum Daily Rainfall](https://data.gov.sg/dataset/rainfall-monthly-maximum-daily-total)
* [Hourly wet buld temperature](https://data.gov.sg/dataset/wet-bulb-temperature-hourly)
* [Monthly mean sunshine hours](https://data.gov.sg/dataset/sunshine-duration-monthly-mean-daily-duration)
* [Surface Air Temperature](https://data.gov.sg/dataset/surface-air-temperature-mean-daily-minimum)

You can also use other datasets for your analysis, make sure to cite the source when you are using them

**To-Do:** *Fill out this cell with the datasets you will use for your analysis. Write a brief description of the contents for each dataset that you choose.*

## Problem Statement

Decide on your problem statement that will guide your analysis for this project. For guidelines, sample prompts, or inspiration, check out the README.

**To-Do:** *Replace this cell with your problem statement.*

Prompts: I'm working in the strategy team for an F1 team 

Problem Statement: Weather plays a huge part in the tactical planning of F1 teams in this sport where differences 100ths of a second in lap time would determine winning or losing .This project aims to analyse the monthly weather patterns of Singapore over the year to anticipate for the upcoming 2023 Singapore Grand Prix in order for my F1 team to come out on top.

Rainfall affects daily activities of Singapore population, hence it is worth analysing rainfall data to identify trends

### Outside Research

Based on your problem statement and your chosen datasets, spend some time doing outside research on how climate change is affecting different industries or additional information that might be relevant. Summarize your findings below. If you bring in any outside tables or charts, make sure you are explicit about having borrowed them. If you quote any text, make sure that it renders as being quoted. **Make sure that you cite your sources.**

**To-Do:** *Fill out this cell with outside research or any additional background information that will support your analysis.*

### Coding Challenges

1. Manually calculate mean:

    Write a function that takes in values and returns the mean of the values. Create a list of numbers that you test on your function to check to make sure your function works!
    
    *Note*: Do not use any mean methods built-in to any Python libraries to do this! This should be done without importing any additional libraries.

In [93]:
# Code: 
n = 10
test = [i for i in range(1, n+1)]
print(test)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [94]:
# Funtion to calculate mean

def my_mean(input):
    return sum(input) / len(input)

my_mean(test)

5.5

2. Manually calculate standard deviation:

    The formula for standard deviation is below:

    $$\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^n(x_i - \mu)^2}$$

    Where $x_i$ represents each value in the dataset, $\mu$ represents the mean of all values in the dataset and $n$ represents the number of values in the dataset.

    Write a function that takes in values and returns the standard deviation of the values using the formula above. Hint: use the function you wrote above to calculate the mean! Use the list of numbers you created above to test on your function.
    
    *Note*: Do not use any standard deviation methods built-in to any Python libraries to do this! This should be done without importing any additional libraries.

In [95]:
# Code:

# Function to calculate standard deviation

def my_std_dev(input):
    n = len(input)
    mean = my_mean(input)
    var = sum((x - mean)**2 for x in input) / n
    std_dev = var**0.5
    return std_dev

my_std_dev(test)

2.8722813232690143

--- 
# Part 2

Part 2 requires knowledge of Pandas, EDA, data cleaning, and data visualization.

---

*All libraries used should be added here*

In [96]:
# Imports:

#Import libraries needed
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Import and Cleaning

### Data Import & Cleaning

Import all the datasets that you selected for this project and go through the following steps at a minimum. You are welcome to do further cleaning as you feel necessary. Make sure to comment your code to showcase the intent behind the data processing step.
1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.
2. Check for missing values and datatype.
3. Check for any obvious issues with the observations.
4. Fix any errors you identified in steps 2-3.
6. Fix any incorrect data types found in step 5.
    - Fix any individual values preventing other columns from being the appropriate type.
    - If the month column data is better analyzed as month and year, create new columns for the same
7. Rename Columns.
    - Column names should be all lowercase.
    - Column names should not contain spaces (underscores will suffice--this allows for using the `df.column_name` method to access columns in addition to `df['column_name']`).
    - Column names should be unique and informative.
8. Drop unnecessary rows (if needed).
9. Merge dataframes that can be merged.
    - Since different climate metrics are in month format, you can merge them into one single dataframe for easier analysis
10. Perform any additional cleaning that you feel is necessary.
11. Save your cleaned and merged dataframes as csv files.

In [129]:
# Code:
# Importing data
sg_weather_2022 = pd.read_csv('../data/DAILYDATA_S108_202209.csv')
sg_weather_2021 = pd.read_csv('../data/DAILYDATA_S108_202109.csv')
sg_weather_2020 = pd.read_csv('../data/DAILYDATA_S108_202009.csv')
sg_weather_2019 = pd.read_csv('../data/DAILYDATA_S108_201909.csv')
sg_weather_2018 = pd.read_csv('../data/DAILYDATA_S108_201809.csv')
sg_weather_2017 = pd.read_csv('../data/DAILYDATA_S108_201709.csv')
sg_weather_2016 = pd.read_csv('../data/DAILYDATA_S108_201609.csv')
sg_weather_2015 = pd.read_csv('../data/DAILYDATA_S108_201509.csv')
sg_weather_2014 = pd.read_csv('../data/DAILYDATA_S108_201409.csv')
sg_weather_2013 = pd.read_csv('../data/DAILYDATA_S108_201309.csv')
sg_weather_2012 = pd.read_csv('../data/DAILYDATA_S108_201209.csv')

### 1. Display the data: print the first 5 rows of each dataframe to your Jupyter notebook.

In [130]:
print("2022 Sept Weather:")
print(sg_weather_2022.head())
print("\n")
print("2021 Sept Weather:")
print(sg_weather_2021.head())
print("\n")
print("2020 Sept Weather:")
print(sg_weather_2020.head())
print("\n")
print("2019 Sept Weather:")
print(sg_weather_2019.head())
print("\n")
print("2018 Sept Weather:")
print(sg_weather_2018.head())
print("\n")
print("2017 Sept Weather:")
print(sg_weather_2017.head())
print("\n")
print("2016 Sept Weather:")
print(sg_weather_2016.head())
print("\n")
print("2015 Sept Weather:")
print(sg_weather_2015.head())
print("\n")
print("2014 Sept Weather:")
print(sg_weather_2014.head())
print("\n")
print("2013 Sept Weather:")
print(sg_weather_2013.head())
print("\n")
print("2012 Sept Weather:")
print(sg_weather_2012.head())
#print("\n")

2022 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2022      9    1                        0.0
1  Marina Barrage  2022      9    2                        4.0
2  Marina Barrage  2022      9    3                        0.0
3  Marina Barrage  2022      9    4                        1.0
4  Marina Barrage  2022      9    5                        3.0

   Highest 30 min Rainfall (mm)  Highest 60 min Rainfall (mm)  \
0                           0.0                           0.0
1                           2.5                           2.5
2                           0.0                           0.0
3                           0.5                           1.0
4                           2.5                           3.0

   Highest 120 min Rainfall (mm)  Mean Temperature (°C)  \
0                            0.0                   29.3
1                            2.5                   27.5
2                            0.0                   28.9
3                            1.0                   28.7
4                            3.0                   28.5

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.7                      27.5                     4.5
1                      31.0                      26.5                     6.4
2                      33.4                      26.6                     8.9
3                      31.2                      26.9                     4.4
4                      33.6                      25.6                     4.3

   Max Wind Speed (km/h)
0                   36.7
1                   29.8
2                   31.3
3                   24.8
4                   40.4


2021 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2021      9    1                       14.6
1  Marina Barrage  2021      9    2                       47.4
2  Marina Barrage  2021      9    3                        0.0
3  Marina Barrage  2021      9    4                        2.6
4  Marina Barrage  2021      9    5                        0.0

   Highest 30 min Rainfall (mm)  Highest 60 min Rainfall (mm)  \
0                          10.8                          13.0
1                          31.8                          37.4
2                           0.0                           0.0
3                           2.4                           2.6
4                           0.0                           0.0

   Highest 120 min Rainfall (mm)  Mean Temperature (°C)  \
0                           14.0                   28.4
1                           41.0                   26.2
2                            0.0                   28.7
3                            2.6                   29.0
4                            0.0                   29.5

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.2                      24.8                     8.8
1                      28.1                      23.4                     7.8
2                      32.9                      25.7                     4.7
3                      34.4                      24.4                     4.6
4                      34.5                      27.2                     5.1

   Max Wind Speed (km/h)
0                   35.0
1                   30.2
2                   23.0
3                   42.0
4                   25.6


2020 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2020      9    1                        0.0
1  Marina Barrage  2020      9    2                        0.0
2  Marina Barrage  2020      9    3                        3.0
3  Marina Barrage  2020      9    4                       45.6
4  Marina Barrage  2020      9    5                       74.2

   Highest 30 min Rainfall (mm)  Highest 60 min Rainfall (mm)  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           1.4                           1.4
3                          14.8                          21.6
4                          26.0                          40.0

   Highest 120 min Rainfall (mm)  Mean Temperature (°C)  \
0                            0.0                   29.1
1                            0.0                   29.3
2                            2.4                   27.8
3                           31.8                   27.5
4                           49.4                   25.8

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.3                      26.9                     4.5
1                      32.9                      27.8                     4.4
2                      31.2                      25.8                     3.5
3                      30.9                      24.7                     4.3
4                      26.8                      23.4                     5.2

   Max Wind Speed (km/h)
0                   28.9
1                   21.7
2                   26.7
3                   25.6
4                   45.0


2019 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2019      9    1                        0.0
1  Marina Barrage  2019      9    2                        0.2
2  Marina Barrage  2019      9    3                        0.0
3  Marina Barrage  2019      9    4                        NaN
4  Marina Barrage  2019      9    5                        0.0

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           0.0                           0.0
1                           0.2                           0.2
2                           0.0                           0.0
3                           NaN                           NaN
4                           0.0                           0.0

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            0.0                   29.8
1                            0.2                   29.8
2                            0.0                   29.9
3                            NaN                    NaN
4                            0.0                    NaN

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.6                      26.5                     4.7
1                      33.8                      27.7                     5.4
2                      33.5                      28.0                     5.4
3                       NaN                       NaN                     NaN
4                       NaN                       NaN                     6.8

   Max Wind Speed (km/h)
0                   19.1
1                   21.6
2                   23.4
3                    NaN
4                   21.2


2018 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2018      9    1                        NaN
1  Marina Barrage  2018      9    2                        NaN
2  Marina Barrage  2018      9    3                        0.6
3  Marina Barrage  2018      9    4                       47.0
4  Marina Barrage  2018      9    5                        NaN

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           NaN                           NaN
1                           NaN                           NaN
2                           0.4                           0.6
3                          37.0                          42.0
4                           NaN                           NaN

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            NaN                    NaN
1                            NaN                    NaN
2                            0.6                   28.2
3                           46.2                    NaN
4                            NaN                    NaN

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                       NaN                       NaN                     NaN
1                       NaN                       NaN                     NaN
2                      31.6                      25.0                     5.4
3                       NaN                       NaN                     5.0
4                       NaN                       NaN                     NaN

   Max Wind Speed (km/h)
0                    NaN
1                    NaN
2                   29.9
3                   41.8
4                    NaN


2017 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2017      9    1                        6.0
1  Marina Barrage  2017      9    2                        0.0
2  Marina Barrage  2017      9    3                        0.0
3  Marina Barrage  2017      9    4                        0.0
4  Marina Barrage  2017      9    5                       11.8

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           3.8                           5.8
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           7.6                           7.6

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            6.0                   29.4
1                            0.0                   29.9
2                            0.0                   29.6
3                            0.0                   29.4
4                            7.6                   29.1

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.0                      25.7                     5.0
1                      33.8                      27.7                     5.8
2                      33.7                      27.8                     6.1
3                      32.4                      27.5                     4.7
4                      32.4                      25.6                     5.0

   Max Wind Speed (km/h)
0                   34.2
1                   26.6
2                   25.6
3                   22.0
4                   29.5


2016 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2016      9    1                        4.6
1  Marina Barrage  2016      9    2                        0.0
2  Marina Barrage  2016      9    3                        0.0
3  Marina Barrage  2016      9    4                        0.0
4  Marina Barrage  2016      9    5                        0.0

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           2.0                           3.8
1                           0.0                           0.0
2                           0.0                           0.0
3                           0.0                           0.0
4                           0.0                           0.0

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            4.6                   27.6
1                            0.0                   29.0
2                            0.0                   29.9
3                            0.0                   29.8
4                            0.0                   28.9

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      32.8                      24.1                    14.0
1                      33.3                      25.9                    13.7
2                      33.9                      26.9                    11.9
3                      33.5                      27.8                    11.2
4                      31.3                      26.9                    14.8

   Max Wind Speed (km/h)
0                   34.9
1                   35.3
2                   31.0
3                   36.7
4                   37.4


2015 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2015      9    1                        0.0
1  Marina Barrage  2015      9    2                        0.0
2  Marina Barrage  2015      9    3                        6.0
3  Marina Barrage  2015      9    4                        0.0
4  Marina Barrage  2015      9    5                        0.0

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           0.0                           0.0
1                           0.0                           0.0
2                           6.0                           6.0
3                           0.0                           0.0
4                           0.0                           0.0

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            0.0                   29.7
1                            0.0                   29.8
2                            6.0                   29.5
3                            0.0                   29.2
4                            0.0                   29.7

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.6                      27.6                     5.3
1                      33.6                      27.6                     6.3
2                      33.3                      25.7                     5.6
3                      32.5                      27.8                     4.4
4                      34.1                      27.6                     4.3

   Max Wind Speed (km/h)
0                   23.4
1                   20.9
2                   30.2
3                   19.1
4                   20.9


2014 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2014      9    1                        0.0
1  Marina Barrage  2014      9    2                        0.0
2  Marina Barrage  2014      9    3                       59.4
3  Marina Barrage  2014      9    4                        0.0
4  Marina Barrage  2014      9    5                        1.8

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           0.0                           0.0
1                           0.0                           0.0
2                          42.2                          56.0
3                           0.0                           0.0
4                           1.6                           1.8

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            0.0                   29.8
1                            0.0                   29.2
2                           59.4                   27.2
3                            0.0                   28.7
4                            1.8                   28.2

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      34.1                      27.5                     6.6
1                      32.5                      27.2                     5.4
2                      32.5                      22.4                     3.3
3                      32.4                      25.2                     3.7
4                      31.3                      24.3                     5.2

   Max Wind Speed (km/h)
0                   20.9
1                   25.9
2                   33.8
3                   17.3
4                   37.1


2013 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2013      9    1                        7.6
1  Marina Barrage  2013      9    2                        0.0
2  Marina Barrage  2013      9    3                        0.0
3  Marina Barrage  2013      9    4                       18.6
4  Marina Barrage  2013      9    5                       33.6

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           NaN                           NaN
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            NaN                   28.2
1                            NaN                   28.1
2                            NaN                   28.9
3                            NaN                   26.8
4                            NaN                   25.9

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      31.5                      25.4                     4.8
1                      32.2                      25.5                     4.3
2                      32.4                      26.7                     4.0
3                      29.5                      23.5                     4.2
4                      27.6                      23.5                     4.2

   Max Wind Speed (km/h)
0                   21.2
1                   18.0
2                   18.4
3                   23.8
4                   33.1


2012 Sept Weather:
          Station  Year  Month  Day  Daily Rainfall Total (mm)  \
0  Marina Barrage  2012      9    1                        0.0
1  Marina Barrage  2012      9    2                        0.0
2  Marina Barrage  2012      9    3                        0.0
3  Marina Barrage  2012      9    4                        2.0
4  Marina Barrage  2012      9    5                        0.0

   Highest 30 Min Rainfall (mm)  Highest 60 Min Rainfall (mm)  \
0                           NaN                           NaN
1                           NaN                           NaN
2                           NaN                           NaN
3                           NaN                           NaN
4                           NaN                           NaN

   Highest 120 Min Rainfall (mm)  Mean Temperature (°C)  \
0                            NaN                   29.8
1                            NaN                   29.6
2                            NaN                   29.6
3                            NaN                   29.5
4                            NaN                   26.6

   Maximum Temperature (°C)  Minimum Temperature (°C)  Mean Wind Speed (km/h)  \
0                      33.7                      27.5                     6.0
1                      34.3                      27.1                     6.1
2                      33.8                      27.3                     6.7
3                      33.0                      26.9                     5.7
4                      28.4                      25.3                     5.6

   Max Wind Speed (km/h)
0                   20.5
1                   20.2
2                   23.0
3                   18.7
4                   31.0

In [131]:
# Check data info

sg_weather_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        30 non-null     object
 1   Year                           30 non-null     int64
 2   Month                          30 non-null     int64
 3   Day                            30 non-null     int64
 4   Daily Rainfall Total (mm)      30 non-null     float64
 5   Highest 30 min Rainfall (mm)   30 non-null     float64
 6   Highest 60 min Rainfall (mm)   30 non-null     float64
 7   Highest 120 min Rainfall (mm)  30 non-null     float64
 8   Mean Temperature (°C)          29 non-null     float64
 9   Maximum Temperature (°C)       29 non-null     float64
 10  Minimum Temperature (°C)       29 non-null     float64
 11  Mean Wind Speed (km/h)         29 non-null     float64
 12  Max Wind Speed (km/h)          29 non-null     float64
dtypes: float64(9), int64(3), object(1)
memory usage: 3.2+ KB

In [137]:
# It was found that the column 5-6 of datasets from 2012-2019 and datasets from 2020-2022 has a very sneaky typo difference
sg_weather_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        30 non-null     object
 1   Year                           30 non-null     int64
 2   Month                          30 non-null     int64
 3   Day                            30 non-null     int64
 4   Daily Rainfall Total (mm)      28 non-null     float64
 5   Highest 30 Min Rainfall (mm)   28 non-null     float64
 6   Highest 60 Min Rainfall (mm)   28 non-null     float64
 7   Highest 120 Min Rainfall (mm)  28 non-null     float64
 8   Mean Temperature (°C)          22 non-null     float64
 9   Maximum Temperature (°C)       22 non-null     float64
 10  Minimum Temperature (°C)       22 non-null     float64
 11  Mean Wind Speed (km/h)         28 non-null     float64
 12  Max Wind Speed (km/h)          28 non-null     float64
dtypes: float64(9), int64(3), object(1)
memory usage: 3.2+ KB

In [138]:
#Changes are made to the datasets of 2020-2022 to prevent any issue when merging data

sg_weather_2022.rename(columns = {
    'Highest 30 min Rainfall (mm)': 'Highest 30 Min Rainfall (mm)',
    'Highest 60 min Rainfall (mm)': 'Highest 60 Min Rainfall (mm)',
    'Highest 120 min Rainfall (mm)': 'Highest 120 Min Rainfall (mm)'
}, inplace = True)

In [139]:
sg_weather_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        30 non-null     object
 1   Year                           30 non-null     int64
 2   Month                          30 non-null     int64
 3   Day                            30 non-null     int64
 4   Daily Rainfall Total (mm)      30 non-null     float64
 5   Highest 30 Min Rainfall (mm)   30 non-null     float64
 6   Highest 60 Min Rainfall (mm)   30 non-null     float64
 7   Highest 120 Min Rainfall (mm)  30 non-null     float64
 8   Mean Temperature (°C)          29 non-null     float64
 9   Maximum Temperature (°C)       29 non-null     float64
 10  Minimum Temperature (°C)       29 non-null     float64
 11  Mean Wind Speed (km/h)         29 non-null     float64
 12  Max Wind Speed (km/h)          29 non-null     float64
dtypes: float64(9), int64(3), object(1)
memory usage: 3.2+ KB

In [140]:
sg_weather_2021.rename(columns = {
    'Highest 30 min Rainfall (mm)': 'Highest 30 Min Rainfall (mm)',
    'Highest 60 min Rainfall (mm)': 'Highest 60 Min Rainfall (mm)',
    'Highest 120 min Rainfall (mm)': 'Highest 120 Min Rainfall (mm)'
}, inplace = True)

In [141]:
sg_weather_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        30 non-null     object
 1   Year                           30 non-null     int64
 2   Month                          30 non-null     int64
 3   Day                            30 non-null     int64
 4   Daily Rainfall Total (mm)      30 non-null     float64
 5   Highest 30 Min Rainfall (mm)   30 non-null     float64
 6   Highest 60 Min Rainfall (mm)   30 non-null     float64
 7   Highest 120 Min Rainfall (mm)  30 non-null     float64
 8   Mean Temperature (°C)          30 non-null     float64
 9   Maximum Temperature (°C)       30 non-null     float64
 10  Minimum Temperature (°C)       30 non-null     float64
 11  Mean Wind Speed (km/h)         30 non-null     float64
 12  Max Wind Speed (km/h)          30 non-null     float64
dtypes: float64(9), int64(3), object(1)
memory usage: 3.2+ KB

In [142]:
sg_weather_2020.rename(columns = {
    'Highest 30 min Rainfall (mm)': 'Highest 30 Min Rainfall (mm)',
    'Highest 60 min Rainfall (mm)': 'Highest 60 Min Rainfall (mm)',
    'Highest 120 min Rainfall (mm)': 'Highest 120 Min Rainfall (mm)'
}, inplace = True)

In [143]:
sg_weather_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        30 non-null     object
 1   Year                           30 non-null     int64
 2   Month                          30 non-null     int64
 3   Day                            30 non-null     int64
 4   Daily Rainfall Total (mm)      30 non-null     float64
 5   Highest 30 Min Rainfall (mm)   30 non-null     float64
 6   Highest 60 Min Rainfall (mm)   30 non-null     float64
 7   Highest 120 Min Rainfall (mm)  30 non-null     float64
 8   Mean Temperature (°C)          30 non-null     float64
 9   Maximum Temperature (°C)       30 non-null     float64
 10  Minimum Temperature (°C)       30 non-null     float64
 11  Mean Wind Speed (km/h)         30 non-null     float64
 12  Max Wind Speed (km/h)          30 non-null     float64
dtypes: float64(9), int64(3), object(1)
memory usage: 3.2+ KB

In [144]:
to_merge = [sg_weather_2021, sg_weather_2020, 
            sg_weather_2019, sg_weather_2018, sg_weather_2017, 
            sg_weather_2016, sg_weather_2015, sg_weather_2014, 
            sg_weather_2013, sg_weather_2012]

sg_sept_weather = sg_weather_2022.append(to_merge, ignore_index = True)

sg_sept_weather.info()

# sg_sept_weather = pd.concat([sg_weather_2021, sg_weather_2020, 
#             sg_weather_2019, sg_weather_2018, sg_weather_2017, 
#             sg_weather_2016, sg_weather_2015, sg_weather_2014, 
#             sg_weather_2013, sg_weather_2012], ignore_index = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        330 non-null    object
 1   Year                           330 non-null    int64
 2   Month                          330 non-null    int64
 3   Day                            330 non-null    int64
 4   Daily Rainfall Total (mm)      319 non-null    float64
 5   Highest 30 Min Rainfall (mm)   259 non-null    float64
 6   Highest 60 Min Rainfall (mm)   259 non-null    float64
 7   Highest 120 Min Rainfall (mm)  259 non-null    float64
 8   Mean Temperature (°C)          308 non-null    float64
 9   Maximum Temperature (°C)       309 non-null    float64
 10  Minimum Temperature (°C)       309 non-null    float64
 11  Mean Wind Speed (km/h)         319 non-null    float64
 12  Max Wind Speed (km/h)          319 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 33.6+ KB

C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\2700299827.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sg_sept_weather = sg_weather_2022.append(to_merge, ignore_index = True)

In [145]:
sg_sept_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        330 non-null    object
 1   Year                           330 non-null    int64
 2   Month                          330 non-null    int64
 3   Day                            330 non-null    int64
 4   Daily Rainfall Total (mm)      319 non-null    float64
 5   Highest 30 Min Rainfall (mm)   259 non-null    float64
 6   Highest 60 Min Rainfall (mm)   259 non-null    float64
 7   Highest 120 Min Rainfall (mm)  259 non-null    float64
 8   Mean Temperature (°C)          308 non-null    float64
 9   Maximum Temperature (°C)       309 non-null    float64
 10  Minimum Temperature (°C)       309 non-null    float64
 11  Mean Wind Speed (km/h)         319 non-null    float64
 12  Max Wind Speed (km/h)          319 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 33.6+ KB

In [148]:
sg_sept_weather.head()

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h)
0,Marina Barrage,2022,9,1,0.0,0.0,0.0,0.0,29.3,33.7,27.5,4.5,36.7
1,Marina Barrage,2022,9,2,4.0,2.5,2.5,2.5,27.5,31.0,26.5,6.4,29.8
2,Marina Barrage,2022,9,3,0.0,0.0,0.0,0.0,28.9,33.4,26.6,8.9,31.3
3,Marina Barrage,2022,9,4,1.0,0.5,1.0,1.0,28.7,31.2,26.9,4.4,24.8
4,Marina Barrage,2022,9,5,3.0,2.5,3.0,3.0,28.5,33.6,25.6,4.3,40.4

In [149]:
sg_sept_weather.tail()

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h)
325,Marina Barrage,2012,9,26,2.0,NaN,NaN,NaN,27.1,29.1,23.6,5.3,38.9
326,Marina Barrage,2012,9,27,56.8,NaN,NaN,NaN,28.4,33.0,22.8,5.2,48.2
327,Marina Barrage,2012,9,28,0.0,NaN,NaN,NaN,28.2,32.1,24.2,4.6,21.6
328,Marina Barrage,2012,9,29,0.0,NaN,NaN,NaN,29.5,33.0,27.2,5.1,23.0
329,Marina Barrage,2012,9,30,0.0,NaN,NaN,NaN,29.4,33.9,27.4,6.0,20.2

In [117]:
# sg_sept_chronological = sg_sept_weather.iloc[::-1]
# sg_sept_chronological.reset_index(drop = True, inplace = True)

In [150]:
# Final checking for data types and null values of dataframe features

sg_sept_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Station                        330 non-null    object
 1   Year                           330 non-null    int64
 2   Month                          330 non-null    int64
 3   Day                            330 non-null    int64
 4   Daily Rainfall Total (mm)      319 non-null    float64
 5   Highest 30 Min Rainfall (mm)   259 non-null    float64
 6   Highest 60 Min Rainfall (mm)   259 non-null    float64
 7   Highest 120 Min Rainfall (mm)  259 non-null    float64
 8   Mean Temperature (°C)          308 non-null    float64
 9   Maximum Temperature (°C)       309 non-null    float64
 10  Minimum Temperature (°C)       309 non-null    float64
 11  Mean Wind Speed (km/h)         319 non-null    float64
 12  Max Wind Speed (km/h)          319 non-null    float64
dtypes: float64(9), int64(3), object(1)
memory usage: 33.6+ KB

In [151]:
# The 2023 Singapore GP will be held on the 17th Sept 2023, the 3rd 
# Sunday of September

# For consitency purposes, we will be using the 3rd Sunday of September
# of every year to run the analysis

# As such, the relevant dates are as follows:

sept_2022 = np.where((sg_sept_weather['Year'] == 2022) & (sg_sept_weather['Day'] ==18)) 
print(sept_2022)
sept_2021 = np.where((sg_sept_weather['Year'] == 2021) & (sg_sept_weather['Day'] ==19))
print(sept_2021)
sept_2020 = np.where((sg_sept_weather['Year'] == 2020) & (sg_sept_weather['Day'] ==20))
print(sept_2020)
sept_2019 = np.where((sg_sept_weather['Year'] == 2019) & (sg_sept_weather['Day'] ==22))
print(sept_2019)
sept_2018 = np.where((sg_sept_weather['Year'] == 2018) & (sg_sept_weather['Day'] ==16))
print(sept_2018)
sept_2017 = np.where((sg_sept_weather['Year'] == 2017) & (sg_sept_weather['Day'] ==17))
print(sept_2017)
sept_2016 = np.where((sg_sept_weather['Year'] == 2016) & (sg_sept_weather['Day'] ==18))
print(sept_2016)
sept_2015 = np.where((sg_sept_weather['Year'] == 2015) & (sg_sept_weather['Day'] ==20))
print(sept_2015)
sept_2014 = np.where((sg_sept_weather['Year'] == 2014) & (sg_sept_weather['Day'] ==21))
print(sept_2014)
sept_2013 = np.where((sg_sept_weather['Year'] == 2013) & (sg_sept_weather['Day'] ==22))
print(sept_2013)
sept_2012 = np.where((sg_sept_weather['Year'] == 2012) & (sg_sept_weather['Day'] ==23))
print(sept_2012)

(array([17], dtype=int64),)
(array([48], dtype=int64),)
(array([79], dtype=int64),)
(array([111], dtype=int64),)
(array([135], dtype=int64),)
(array([166], dtype=int64),)
(array([197], dtype=int64),)
(array([229], dtype=int64),)
(array([260], dtype=int64),)
(array([291], dtype=int64),)
(array([322], dtype=int64),)

In [152]:
sept_week3_sun = sg_sept_weather.iloc[[17],:]
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[48],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[79],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[111],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[135],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[166],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[197],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[229],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[260],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[291],:])
sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[322],:])

C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[48],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[79],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[111],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[135],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[166],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[197],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[229],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[260],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[291],:])
C:\Users\Admin\AppData\Local\Temp\ipykernel_22876\991394347.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sept_week3_sun = sept_week3_sun.append(sg_sept_weather.iloc[[322],:])

In [156]:
# sept_week3_sun will be the df that we will be working with for the rest of this project

sept_week3_sun.reset_index(drop = True, inplace = True)
sept_week3_sun

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h)
0,Marina Barrage,2022,9,18,60.8,16.4,21.8,38.6,26.2,28.3,22.6,6.2,28.2
1,Marina Barrage,2021,9,19,1.2,1.0,1.0,1.0,28.0,29.7,25.5,7.0,41.1
2,Marina Barrage,2020,9,20,0.0,0.0,0.0,0.0,29.5,32.7,28.1,5.7,24.1
3,Marina Barrage,2019,9,22,0.0,0.0,0.0,0.0,NaN,NaN,NaN,7.2,28.4
4,Marina Barrage,2018,9,16,0.0,0.0,0.0,0.0,29.0,31.8,27.7,6.5,31.0
5,Marina Barrage,2017,9,17,17.8,17.4,17.4,17.4,29.3,34.9,25.5,5.8,28.4
6,Marina Barrage,2016,9,18,54.4,40.2,53.0,54.2,28.9,32.8,22.1,11.9,51.5
7,Marina Barrage,2015,9,20,0.0,0.0,0.0,0.0,29.8,34.0,26.7,4.3,16.6
8,Marina Barrage,2014,9,21,3.4,1.6,2.6,3.0,28.1,31.7,24.8,5.0,24.8
9,Marina Barrage,2013,9,22,0.0,NaN,NaN,NaN,29.9,33.1,27.8,5.4,20.2
10,Marina Barrage,2012,9,23,0.0,NaN,NaN,NaN,29.2,33.0,26.8,3.8,20.9

In [158]:
sept_week3_sun.to_csv('sept_week3_sun.csv')

In [159]:
# Proceed to the last cleaning of data, which is to remove the entries with null values
sept_week3_sun = sept_week3_sun.dropna(how = 'any', axis = 0)

In [160]:
sept_week3_sun

,Station,Year,Month,Day,Daily Rainfall Total (mm),Highest 30 Min Rainfall (mm),Highest 60 Min Rainfall (mm),Highest 120 Min Rainfall (mm),Mean Temperature (°C),Maximum Temperature (°C),Minimum Temperature (°C),Mean Wind Speed (km/h),Max Wind Speed (km/h)
0,Marina Barrage,2022,9,18,60.8,16.4,21.8,38.6,26.2,28.3,22.6,6.2,28.2
1,Marina Barrage,2021,9,19,1.2,1.0,1.0,1.0,28.0,29.7,25.5,7.0,41.1
2,Marina Barrage,2020,9,20,0.0,0.0,0.0,0.0,29.5,32.7,28.1,5.7,24.1
4,Marina Barrage,2018,9,16,0.0,0.0,0.0,0.0,29.0,31.8,27.7,6.5,31.0
5,Marina Barrage,2017,9,17,17.8,17.4,17.4,17.4,29.3,34.9,25.5,5.8,28.4
6,Marina Barrage,2016,9,18,54.4,40.2,53.0,54.2,28.9,32.8,22.1,11.9,51.5
7,Marina Barrage,2015,9,20,0.0,0.0,0.0,0.0,29.8,34.0,26.7,4.3,16.6
8,Marina Barrage,2014,9,21,3.4,1.6,2.6,3.0,28.1,31.7,24.8,5.0,24.8

In [161]:
sept_week3_sun.to_csv('cleaned_sept_week3_sun.csv')

### Data Dictionary

Now that we've fixed our data, and given it appropriate names, let's create a [data dictionary](http://library.ucmerced.edu/node/10249). 

A data dictionary provides a quick overview of features/variables/columns, alongside data types and descriptions. The more descriptive you can be, the more useful this document is.

Example of a Fictional Data Dictionary Entry: 

|Feature|Type|Dataset|Description|
|---|---|---|---|
|**county_pop**|*integer*|2010 census|The population of the county (units in thousands, where 2.5 represents 2500 people).| 
|**per_poverty**|*float*|2010 census|The percent of the county over the age of 18 living below the 200% of official US poverty rate (units percent to two decimal places 98.10 means 98.1%)|

[Here's a quick link to a short guide for formatting markdown in Jupyter notebooks](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html).

Provided is the skeleton for formatting a markdown table, with columns headers that will help you create a data dictionary to quickly summarize your data, as well as some examples. **This would be a great thing to copy and paste into your custom README for this project.**

*Note*: if you are unsure of what a feature is, check the source of the data! This can be found in the README.

**To-Do:** *Edit the table below to create your own data dictionary for the datasets you chose.*

|Feature|Type|Dataset|Description|
|---|---|---|---|
|total_rainfall|float|rainfall-monthly-total|Total rainfall in mm|

## Exploratory Data Analysis

Complete the following steps to explore your data. You are welcome to do more EDA than the steps outlined here as you feel necessary:
1. Summary Statistics.
2. Use a **dictionary comprehension** to apply the standard deviation function you create in part 1 to each numeric column in the dataframe.  **No loops**.
    - Assign the output to variable `sd` as a dictionary where: 
        - Each column name is now a key 
        - That standard deviation of the column is the value 
        - *Example Output :* `{'rainfall-monthly-total': xxx, 'no_of_rainy_days': xxx, ...}`
3. Investigate trends in the data.
    - Using sorting and/or masking (along with the `.head()` method to avoid printing our entire dataframe), consider questions relevant to your problem statement. Some examples are provided below (but feel free to change these questions for your specific problem):
        - Which month have the highest and lowest total rainfall in 1990, 2000, 2010 and 2020?
        - Which year have the highest and lowest total rainfall in the date range of analysis?
        - Which month have the highest and lowest number of rainy days in 1990, 2000, 2010 and 2020?
        - Which year have the highest and lowest number of rainy days in the date range of analysis?
        - Are there any outliers months in the dataset?
       
    - **The above 5 questions are compulsory. Feel free to explore other trends based on the datasets that you have choosen for analysis. You should comment on your findings at each step in a markdown cell below your code block**. Make sure you include at least one example of sorting your dataframe by a column, and one example of using boolean filtering (i.e., masking) to select a subset of the dataframe.

In [124]:
#Code:

In [125]:
#Code:

**To-Do:** *Edit this cell with your findings on trends in the data (step 3 above).*

## Visualize the Data

There's not a magic bullet recommendation for the right number of plots to understand a given dataset, but visualizing your data is *always* a good idea. Not only does it allow you to quickly convey your findings (even if you have a non-technical audience), it will often reveal trends in your data that escaped you when you were looking only at numbers. It is important to not only create visualizations, but to **interpret your visualizations** as well.

**Every plot should**:
- Have a title
- Have axis labels
- Have appropriate tick labels
- Text is legible in a plot
- Plots demonstrate meaningful and valid relationships
- Have an interpretation to aid understanding

Here is an example of what your plots should look like following the above guidelines. Note that while the content of this example is unrelated, the principles of visualization hold:

![](https://snag.gy/hCBR1U.jpg)
*Interpretation: The above image shows that as we increase our spending on advertising, our sales numbers also tend to increase. There is a positive correlation between advertising spending and sales.*

---

Here are some prompts to get you started with visualizations. Feel free to add additional visualizations as you see fit:
1. Use Seaborn's heatmap with pandas `.corr()` to visualize correlations between all numeric features.
    - Heatmaps are generally not appropriate for presentations, and should often be excluded from reports as they can be visually overwhelming. **However**, they can be extremely useful in identify relationships of potential interest (as well as identifying potential collinearity before modeling).
    - Please take time to format your output, adding a title. Look through some of the additional arguments and options. (Axis labels aren't really necessary, as long as the title is informative).
2. Visualize distributions using histograms. If you have a lot, consider writing a custom function and use subplots.
    - *OPTIONAL*: Summarize the underlying distributions of your features (in words & statistics)
         - Be thorough in your verbal description of these distributions.
         - Be sure to back up these summaries with statistics.
         - We generally assume that data we sample from a population will be normally distributed. Do we observe this trend? Explain your answers for each distribution and how you think this will affect estimates made from these data.
3. Plot and interpret boxplots. 
    - Boxplots demonstrate central tendency and spread in variables. In a certain sense, these are somewhat redundant with histograms, but you may be better able to identify clear outliers or differences in IQR, etc.
    - Multiple values can be plotted to a single boxplot as long as they are of the same relative scale (meaning they have similar min/max values).
    - Each boxplot should:
        - Only include variables of a similar scale
        - Have clear labels for each variable
        - Have appropriate titles and labels
4. Plot and interpret scatter plots to view relationships between features. Feel free to write a custom function, and subplot if you'd like. Functions save both time and space.
    - Your plots should have:
        - Two clearly labeled axes
        - A proper title
        - Colors and symbols that are clear and unmistakable
5. Additional plots of your choosing.
    - Are there any additional trends or relationships you haven't explored? Was there something interesting you saw that you'd like to dive further into? It's likely that there are a few more plots you might want to generate to support your narrative and recommendations that you are building toward. **As always, make sure you're interpreting your plots as you go**.

Some ideas for plots that can be generated:

- Plot the histogram of the rainfall data with various bins and comment on the distribution of the data - is it centered, skewed?
- Plot the box-and-whiskers plot. Comment on the different quartiles and identify any outliers in the dataset. 
- Is there a correlation between the number of rainy days and total rainfall in the month? What kind of correlation do your suspect? Does the graph show the same?

In [126]:
# Code

## Conclusions and Recommendations

Based on your exploration of the data, what are you key takeaways and recommendations? Make sure to answer your question of interest or address your problem statement here.

**To-Do:** *Edit this cell with your conclusions and recommendations.*

Don't forget to create your README!

**To-Do:** *If you combine your problem statement, data dictionary, brief summary of your analysis, and conclusions/recommendations, you have an amazing README.md file that quickly aligns your audience to the contents of your project.* Don't forget to cite your data sources!